### ISSUE TITLE
请教调用网络接口的时候怎么传参呢？

### ISSUE THREAD

**Issue by nongjuanfeng** [KevinnZou/compose-pagingList#5]
<img width="756" alt="image" src="https://github.com/KevinnZou/compose-pagingList/assets/56825407/73e045b9-8c5c-42f6-b18c-4b8f9b035b5d">

如图

这里是调用 `val areaDevices = viewModel.areaDevices.collectAsLazyPagingItems()`，怎么动态传参给 getAreaDevices 函数呢？

我现在是通过在函数外面维护一个变量实现，但是这样就不是函数编程了。

**Comment by KevinnZou** [comment]
你好，我有点不太确定我有没有明白你的意思，你是指你的loadData函数也就是getAreaDevices需要除了page以外的参数该怎么传递吗？这样的话直接在viewmodel中维护一个变量就行了，loaddata中直接使用即可, 简单例子如下：
```
class viewModel() : ViewModel() {

    var param1 = "hhhh"
    
    val pager = easyPager {
        return@easyPager brandIndexService.getBrandIndex(
            param1,
            it
        )
    }
}
```
如果不是这个意思麻烦你描述的稍微再详细一点，谢谢！

**Comment by nongjuanfeng** [comment]
> 你好，我有点不太确定我有没有明白你的意思，你是指你的loadData函数也就是getAreaDevices需要除了page以外的参数该怎么传递吗？这样的话直接在viewmodel中维护一个变量就行了，loaddata中直接使用即可, 简单例子如下：
> 
> ```
> class viewModel() : ViewModel() {
> 
>     var param1 = "hhhh"
>     
>     val pager = easyPager {
>         return@easyPager brandIndexService.getBrandIndex(
>             param1,
>             it
>         )
>     }
> }
> ```
> 
> 如果不是这个意思麻烦你描述的稍微再详细一点，谢谢！

没错！
我现在就是这样，在函数外面维护一个变量。
但是这样有时会出现问题，例如，这个 loadData 同时有 3 个地方调用，这时这个外部的变量就可能因为并发问题，导致读取的时候出现不确定性。

**Comment by KevinnZou** [comment]
你这个情况确实我确实没考虑到，因为一般一个分页列表的loaddata方法只会服务于该分页列表，触发时机由PagingSource控制。官方的Paging使用指南中也是单独调用的，多处调用的场景是什么？考虑抽离一个单独的loaddata方法仅服务于分页列表？如果实在存在同时调用的并发情况，可能只能考虑采用并发安全的类型来处理变量。

**Comment by KevinnZou** [comment]
你这个情况确实我确实没考虑到，因为一般一个分页列表的loaddata方法只会服务于该分页列表，触发时机由PagingSource控制。官方的Paging使用指南中也是单独调用的，多处调用的场景是什么？考虑抽离一个单独的loaddata方法仅服务于分页列表？如果实在存在同时调用的并发情况，可能只能考虑采用并发安全的类型来处理变量。
